yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('', views.index, name='index'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow, name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.contrib import admin
# импорт include позволит использовать адреса, включенные в приложения
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    # импорт информации из приложения posts
    path('group/<slug>/', include('posts.urls'), name='group_list'),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    # Если DEBUG=True в настройках
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # раздаем статичные файлы с сервера разработки runserver
    urlpatterns += staticfiles_urlpatterns()

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.internal_server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts')
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        related_name='posts',
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост')
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        null=True,
        blank=True,
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()
    image = models.ImageField(
        'Картинка',
        upload_to='groups/',
        blank=True
    )

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self) -> str:
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField('Текст', help_text='Текст нового комментария')
    created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self) -> str:
        return self.text[:200]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        ordering = ('author',)
        constraints = [
            models.UniqueConstraint(
                fields=['author', 'user'], name='unique_follower')
        ]

yatube/posts/forms.py
from django import forms

from .models import Post, Group, Comment


class PostForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea)
    group = forms.ModelChoiceField(queryset=Group.objects.all(),
                                   required=False)
    image = forms.ImageField(required=False)

    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        label = {
            'text': 'Текст поста',
            'group': 'Группа поста',
            'image': 'Изображение',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        label = {
            'text': 'Комментарий к посту'
        }

yatube/posts/views.py
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.cache import cache_page

from .models import User, Post, Group, Follow, get_user_model
from .forms import PostForm, CommentForm

PAGE_NMB = 10


@cache_page(20, key_prefix='index_page')
def index(request):
    post_list = Post.objects.all().select_related(
        'group').order_by('-pub_date')
    paginator = Paginator(post_list, PAGE_NMB)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    index = True
    context = {
        'post_list': post_list,
        'page_obj': page_obj,
        'index': index,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all().order_by('-pub_date')
    paginator = Paginator(posts, PAGE_NMB)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_user_model()
    user = get_object_or_404(author, username=username)
    posts = user.posts.all()
    posts_count = posts.count()
    paginator = Paginator(posts, PAGE_NMB)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user, author=user).exists()
    else:
        following = False
    context = {
        'author': user,
        'posts': posts,
        'page_obj': page_obj,
        'posts_count': posts_count,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    queryset = Post.objects.select_related('author', 'group')
    post = get_object_or_404(queryset, id=post_id)
    author_posts = post.author.posts.count()
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'post': post,
        'author_posts': author_posts,
        'form': form,
        'post_id': post_id,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST or None,
                        files=request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post = form.save()
            return redirect('posts:profile',
                            username=post.author)
        return render(request, 'posts/create_post.html',
                      {'form': form})
    else:
        form = PostForm(request.POST or None,
                        files=request.FILES or None)
        return render(request, 'posts/create_post.html',
                      {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    is_edit = True
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    else:
        request.method == 'POST'
        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
            instance=post)
        if not form.is_valid():
            return render(request, 'posts/create_post.html',
                          {'form': form, 'is_edit': is_edit, 'post': post})
        else:
            post.save()
            return redirect('posts:post_detail', post_id=post_id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect('posts:post_detail', post_id=post_id)
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, PAGE_NMB)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    follow = True
    context = {
        'page_obj': page_obj,
        'paginator': paginator,
        'follow': follow,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:follow_index')

yatube/templates/posts/comment.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p> {{ comment.text|linebreaksbr}} </p>
    </div>
  </div>
{% endfor %}

yatube/templates/posts/create_post.html
<!DOCTYPE html> 
<html lang="ru">
{%extends 'base.html'%}
{%block title%} Новый пост {% endblock %}
{% block content %}
<body>
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">       
              Новый пост             
            </div>
            <div class="card-body">
              <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
                {% csrf_token %}
                {% for field in form %}
                  <div class="form-group row my-3 p-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                    </label>
                    {% if field.label == 'Group' %}
                      <select name="group" class="form-control" id="id_group">
                        <option value="" selected> -------- </option>
                        <option value="1"> Лев Толстой – зеркало русской революции</option>
                      </select>
                      <small id="id_group-help" class="form-text text-muted">
                        Группа, к которой будет относиться пост
                      </small>
                    {% else %}
                      {{ field }}
                      {% if field.label == 'Text' %}
                        <small id="id_text-help" class="form-text text-muted"> 
                          Текст нового поста 
                        </small>
                      {% else %}
                        <small id="id_image-help" class="form-text text-muted"> 
                          Картинка для нового поста 
                        </small>
                      {% endif %}
                    {% endif %}
                  </div>
                {% endfor %}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}               
                  </button> 
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</body>
{% endblock %}
</html>

yatube/templates/posts/follow.html
{%extends 'base.html'%}
{% load thumbnail %}
{%block title%} Подписка {%endblock%}
{%block content%}
  <head>
    <h1> Подписка </h1>
  </head>
  {% include 'includes/switcher.html' %}
  <body>
    <main>
      <div class="container py-5">     
        <article>
          {% include 'includes/post_structure.html' %}
        </article>
        {% include 'includes/paginator.html' %}
      </div>  
{%endblock%}

yatube/templates/posts/group_list.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
{%extends 'base.html'%}
{% block header %}{{ group.title }}{% endblock %}
{%block content%}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    <article>
      {% for post in posts %}
        <ul>
          <li>
            {% if post.author != None %}
              <a href="{% url 'posts:profile' post.author %}"> {{ post.author.get_full_name }} </a>
            {% else %}
              <p> admin </p>
            {% endif %}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"j F Y"}}
          </li>
        </ul>
        <p> {{ post.text }} </p>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'includes/paginator.html' %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/index.html
{%extends 'base.html'%} 
{% load thumbnail %}
{%block title%} Последние обновления на сайте {%endblock%} 
{%block content%} 
  <head> 
    <h2>Последние обновления на сайте </h2> 
  </head> 
  {% include 'includes/switcher.html' %}
  <body> 
    <main>
      <div class="container py-5">
        {% for post in page_obj %}
          <article>
            {% include 'includes/post_structure.html' %}
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
          </article>
        {% endfor %}
      </div>
      {% include 'includes/paginator.html' %} 
{%endblock%} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{%block title %} Пост {%endblock%}
{%block content%}
  <body>       
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"j F Y"}}
            </li>
            <li class="list-group-item">
              Группа: 
                {% if post.group.title != None %} {{ post.group.title }}
                {% else %}
                  <p> группа не установлена </p>
                {% endif %}
                <br>
                {% if post.group.title != None %}
                  <a href="{% url 'posts:group_posts' post.group.slug %}"> все записи группы </a>
                {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {% if post.author != None %} 
              <a href="{% url 'posts:profile' post.author %}"> {{ post.author.get_full_name }} </a>
              {% else %}
                <p> admin </p>
              {% endif %}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span> {{ author_posts }} </span>
            </li>
            <li class="list-group-item">
              {% if post.author.username != None %}
                <a href="{% url 'posts:profile' post.author.username %}">
                  Все посты пользователя
                </a>
              {% endif%}
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p> {{ post.text }} </p>
          <a href="{% url 'posts:post_edit' post.id %}"> Редактировать </a>
        </article>
      {% include 'posts/comment.html' %} 
      </div>
    </main>
  </body>
{% endblock %}

yatube/templates/posts/profile.html
<!DOCTYPE html>
<html lang="ru">
{%extends 'base.html'%}
{% load thumbnail %}
{%block title%} Профайл пользователя {{ author.get_full_name }} {%endblock%}
{%block content%}
  <div class="container py-5">
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
      <h3>Всего постов: {{ posts_count }} </h3>
      {% if following %}
        <a class="btn btn-lg btn-light" href="{% url 'posts:profile_unfollow' author.username %}" role="button">
          Отписаться
        </a>
      {% else %}
        <a class="btn btn-lg btn-primary" href="{% url 'posts:profile_follow' author.username %}" role="button">
          Подписаться
        </a>
      {% endif %}
      <article>
        {% for post in page_obj %}
          <ul>
            <li>
              Дата публикации: {{post.pub_date|date:"j F Y"}}
            </li>
          </ul>
          <p> {{ post.text }} </p>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <a href="{% url 'posts:post_detail' post.id %}"> подробная информация </a>
          <br>
          {% if post.group.title != None %}
            <a href="{% url 'posts:group_posts' post.group.slug %}"> все записи группы </a>
          {% else %}
            <p> группа не установлена </p>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      </article>       
      {% include 'includes/paginator.html' %}
  </div>
{% endblock %}
</html>

yatube/templates/posts/update_post.html
<!DOCTYPE html> 
<html lang="ru">
{%extends 'base.html'%}
{%block title%} Редактировать пост {% endblock %}
{% block content %}
<body>	   
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">       
              Редактировать пост             
            </div>
            <div class="card-body">        
              <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' %}">
                <input type="hidden" name="csrfmiddlewaretoken" value="">
                {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {% if field.label == 'Group' %}
                    <select name="group" class="form-control" id="id_group">
                      <option value="" selected> -------- </option>
                      <option value="1"> Лев Толстой – зеркало русской революции</option>
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  {% else %}
                    {{ field }}
                    {% if field.label == 'Text' %}
                      <small id="id_text-help" class="form-text text-muted"> 
                        Текст обновленного поста 
                      </small>
                    {% else %}
                      <small id="id_image-help" class="form-text text-muted"> 
                        Картинка для поста 
                      </small>
                    {% endif %}
                  {% endif %}
                </div>
              {% endfor %}               
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    Сохранить
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</body>
{% endblock %}
</html>